// learningPathData.js
export const learningPathData = [
    { id: 1, name: "Accidents", status: "completed", icon: "💥", level: 1 },
    { id: 2, name: "Adventure", status: "active", icon: "⛰️", level: 2 },
    { id: 3, name: "Advertising", status: "active", icon: "📢", level: 3 },
    { id: 4, name: "Advice", status: "skipped", icon: "🤔", level: 2 },
    { id: 5, name: "Africa", status: "locked", icon: "🦓", level: 3 },
    { id: 6, name: "Age", status: "completed", icon: "⏳", level: 1 },
    { id: 7, name: "Airports", status: "locked", icon: "🛬", level: 2 },
    { id: 8, name: "Anger", status: "active", icon: "😡", level: 1 },
    { id: 9, name: "Animals", status: "locked", icon: "🐾", level: 1 },
    { id: 10, name: "Appearance", status: "locked", icon: "👀", level: 2 },
    { id: 11, name: "Appliances", status: "locked", icon: "🎛️", level: 1 },
    { id: 12, name: "Art", status: "locked", icon: "🎨", level: 3 },
    { id: 13, name: "Artificial Intelligence", status: "locked", icon: "💭", level: 3 },
    { id: 14, name: "Asia", status: "locked", icon: "🐅", level: 3 },
    { id: 15, name: "Astrology", status: "locked", icon: "♈", level: 2 },
    { id: 16, name: "Astronomy", status: "locked", icon: "🔭", level: 3 },
    { id: 17, name: "Atmosphere", status: "locked", icon: "💨", level: 2 },
    { id: 18, name: "Babies", status: "locked", icon: "👶", level: 1 },
    { id: 19, name: "Bad habits", status: "locked", icon: "🚬", level: 2 },
    { id: 20, name: "Banking", status: "locked", icon: "🏦", level: 3 },
    { id: 21, name: "Beauty", status: "locked", icon: "💅", level: 1 },
    { id: 22, name: "Birds", status: "locked", icon: "🐦", level: 1 },
    { id: 23, name: "Blogs", status: "locked", icon: "✍️", level: 2 },
    { id: 24, name: "Books", status: "locked", icon: "📚", level: 1 },
    { id: 25, name: "Business", status: "locked", icon: "💼", level: 3 },
    { id: 26, name: "Camping", status: "locked", icon: "🏕️", level: 2 },
    { id: 27, name: "Cars", status: "locked", icon: "🚗", level: 1 },
    { id: 28, name: "Cats", status: "locked", icon: "🐱", level: 1 },
    { id: 29, name: "Celebrations", status: "locked", icon: "🎉", level: 2 },
    { id: 30, name: "Charity", status: "locked", icon: "💖", level: 3 },
    { id: 31, name: "Childhood", status: "locked", icon: "🧸", level: 1 },
    { id: 32, name: "Chocolate", status: "locked", icon: "🍫", level: 1 },
    { id: 33, name: "Cities", status: "locked", icon: "🏙️", level: 2 },
    { id: 34, name: "Cleanliness", status: "locked", icon: "🧼", level: 1 },
    { id: 35, name: "Climate", status: "locked", icon: "☀️", level: 2 },
    { id: 36, name: "Clothes", status: "locked", icon: "👕", level: 1 },
    { id: 37, name: "Coffee", status: "locked", icon: "☕", level: 1 },
    { id: 38, name: "Colors", status: "locked", icon: "🌈", level: 1 },
    { id: 39, name: "Communication", status: "locked", icon: "💬", level: 2 },
    { id: 40, name: "Computers", status: "locked", icon: "💻", level: 2 },
    { id: 41, name: "Cooking", status: "locked", icon: "🍳", level: 1 },
    { id: 42, name: "Countries", status: "locked", icon: "🗺️", level: 2 },
    { id: 43, name: "Courage", status: "locked", icon: "🦁", level: 3 },
    { id: 44, name: "Crime", status: "locked", icon: "🚨", level: 3 },
    { id: 45, name: "Culture", status: "locked", icon: "🎭", level: 2 },
    { id: 46, name: "Customer service", status: "locked", icon: "📞", level: 2 },
    { id: 47, name: "Dance", status: "locked", icon: "💃", level: 1 },
    { id: 48, name: "Danger", status: "locked", icon: "⚠️", level: 2 },
    { id: 49, name: "Death", status: "locked", icon: "💀", level: 3 },
    { id: 50, name: "Decision making", status: "locked", icon: "🤔", level: 3 },
    { id: 51, name: "Democracy", status: "locked", icon: "🗳️", level: 3 },
    { id: 52, name: "Dentists", status: "locked", icon: "🦷", level: 1 },
    { id: 53, name: "Diet", status: "locked", icon: "🍎", level: 1 },
    { id: 54, name: "Dinosaurs", status: "locked", icon: "🦖", level: 2 },
    { id: 55, name: "Disasters", status: "locked", icon: "🌪️", level: 3 },
    { id: 56, name: "Dogs", status: "locked", icon: "🐕", level: 1 },
    { id: 57, name: "Dreams", status: "locked", icon: "😴", level: 2 },
    { id: 58, name: "Driving", status: "locked", icon: "🛣️", level: 2 },
    { id: 59, name: "Drugs", status: "locked", icon: "💊", level: 3 },
    { id: 60, name: "Ecology", status: "locked", icon: "♻️", level: 3 },
    { id: 61, name: "Economy", status: "locked", icon: "💰", level: 3 },
    { id: 62, name: "Education", status: "locked", icon: "🎓", level: 2 },
    { id: 63, name: "Emotions", status: "locked", icon: "😊", level: 1 },
    { id: 64, name: "Energy", status: "locked", icon: "⚡", level: 2 },
    { id: 65, name: "Entertainment", status: "locked", icon: "🎬", level: 1 },
    { id: 66, name: "Environment", status: "locked", icon: "🌳", level: 2 },
    { id: 67, name: "Ethics", status: "locked", icon: "⚖️", level: 3 },
    { id: 68, name: "Europe", status: "locked", icon: "🏛️", level: 3 },
    { id: 69, name: "Exercise", status: "locked", icon: "💪", level: 1 },
    { id: 70, name: "Fairy tales", status: "locked", icon: "🧚", level: 1 },
    { id: 71, name: "Family", status: "locked", icon: "👨‍👩‍👧‍👦", level: 1 },
    { id: 72, name: "Fashion", status: "locked", icon: "👗", level: 2 },
    { id: 73, name: "Fears", status: "locked", icon: "😱", level: 2 },
    { id: 74, name: "Feelings", status: "locked", icon: "❤️", level: 1 },
    { id: 75, name: "Festivals", status: "locked", icon: "🥳", level: 2 },
    { id: 76, name: "Films", status: "locked", icon: "🎥", level: 1 },
    { id: 77, name: "Finance", status: "locked", icon: "📈", level: 3 },
    { id: 78, name: "Fire", status: "locked", icon: "🔥", level: 2 },
    { id: 79, name: "First aid", status: "locked", icon: "🩹", level: 2 },
    { id: 80, name: "Flowers", status: "locked", icon: "🌸", level: 1 },
    { id: 81, name: "Food", status: "locked", icon: "🍔", level: 1 },
    { id: 82, name: "Friendship", status: "locked", icon: "🤝", level: 1 },
    { id: 83, name: "Fun", status: "locked", icon: "😄", level: 1 },
    { id: 84, name: "Future", status: "locked", icon: "🔮", level: 2 },
    { id: 85, name: "Games", status: "locked", icon: "🎲", level: 1 },
    { id: 86, name: "Gardening", status: "locked", icon: "👨‍🌾", level: 2 },
    { id: 87, name: "Gender", status: "locked", icon: "🚻", level: 3 },
    { id: 88, name: "Generosity", status: "locked", icon: "🎁", level: 2 },
    { id: 89, name: "Genetics", status: "locked", icon: "🧬", level: 3 },
    { id: 90, name: "Geography", status: "locked", icon: "🌍", level: 2 },
    { id: 91, name: "Goals", status: "locked", icon: "🎯", level: 2 },
    { id: 92, name: "Government", status: "locked", icon: "🏛️", level: 3 },
    { id: 93, name: "Happiness", status: "locked", icon: "😊", level: 1 },
    { id: 94, name: "Health", status: "locked", icon: "❤️‍🩹", level: 1 },
    { id: 95, name: "History", status: "locked", icon: "📜", level: 2 },
    { id: 96, name: "Hobbies", status: "locked", icon: "🎨", level: 1 },
    { id: 97, name: "Homes", status: "locked", icon: "🏠", level: 1 },
    { id: 98, name: "Hope", status: "locked", icon: "🌟", level: 2 },
    { id: 99, name: "Hotels", status: "locked", icon: "🏨", level: 2 },
    { id: 100, name: "Human body", status: "locked", icon: "👤", level: 1 },
    { id: 101, name: "Humor", status: "locked", icon: "😂", level: 1 },
    { id: 102, name: "Ideas", status: "locked", icon: "💡", level: 2 },
    { id: 103, name: "Immigration", status: "locked", icon: "🛂", level: 3 },
    { id: 104, name: "Inequality", status: "locked", icon: "⚖️", level: 3 },
    { id: 105, name: "Information", status: "locked", icon: "ℹ️", level: 2 },
    { id: 106, name: "Insects", status: "locked", icon: "🐛", level: 1 },
    { id: 107, name: "Internet", status: "locked", icon: "🌐", level: 2 },
    { id: 108, name: "Inventions", status: "locked", icon: " inventing", level: 3 },
    { id: 109, name: "Investments", status: "locked", icon: "📈", level: 3 },
    { id: 110, name: "Job", status: "locked", icon: "💼", level: 1 },
    { id: 111, name: "Justice", status: "locked", icon: "⚖️", level: 3 },
    { id: 112, name: "Kids", status: "locked", icon: "👧", level: 1 },
    { id: 113, name: "Knowledge", status: "locked", icon: "🧠", level: 2 },
    { id: 114, name: "Laughter", status: "locked", icon: "🤣", level: 1 },
    { id: 115, name: "Law", status: "locked", icon: "👨‍⚖️", level: 3 },
    { id: 116, name: "Leadership", status: "locked", icon: "👑", level: 3 },
    { id: 117, name: "Learning", status: "locked", icon: "📖", level: 2 },
    { id: 118, name: "Leisure", status: "locked", icon: "🏖️", level: 1 },
    { id: 119, name: "Life", status: "locked", icon: "🧬", level: 1 },
    { id: 120, name: "Light", status: "locked", icon: "💡", level: 2 },
    { id: 121, name: "Literature", status: "locked", icon: "✍️", level: 2 },
    { id: 122, name: "Love", status: "locked", icon: "❤️", level: 1 },
    { id: 123, name: "Luck", status: "locked", icon: "🍀", level: 1 },
    { id: 124, name: "Machines", status: "locked", icon: "⚙️", level: 2 },
    { id: 125, name: "Magazines", status: "locked", icon: "📰", level: 1 },
    { id: 126, name: "Magic", status: "locked", icon: "✨", level: 2 },
    { id: 127, name: "Marketing", status: "locked", icon: "📊", level: 3 },
    { id: 128, name: "Marriage", status: "locked", icon: "👰", level: 2 },
    { id: 129, name: "Mathematics", status: "locked", icon: "➕", level: 2 },
    { id: 130, name: "Media", status: "locked", icon: "📺", level: 2 },
    { id: 131, name: "Medicine", status: "locked", icon: "⚕️", level: 2 },
    { id: 132, name: "Memory", status: "locked", icon: "🧠", level: 1 },
    { id: 133, name: "Men", status: "locked", icon: "👨", level: 1 },
    { id: 134, name: "Mental health", status: "locked", icon: "🧘‍♀️", level: 2 },
    { id: 135, name: "Money", status: "locked", icon: "💸", level: 1 },
    { id: 136, name: "Mountains", status: "locked", icon: "⛰️", level: 2 },
    { id: 137, name: "Movies", status: "locked", icon: "🎬", level: 1 },
    { id: 138, name: "Museums", status: "locked", icon: "🏛️", level: 2 },
    { id: 139, name: "Music", status: "locked", icon: "🎶", level: 1 },
    { id: 140, name: "Mystery", status: "locked", icon: "🔍", level: 2 },
    { id: 141, name: "Nature", status: "locked", icon: "🌿", level: 1 },
    { id: 142, name: "Newspapers", status: "locked", icon: "📰", level: 1 },
    { id: 143, name: "Noise", status: "locked", icon: "🔊", level: 1 },
    { id: 144, name: "North America", status: "locked", icon: "🗽", level: 3 },
    { id: 145, name: "Oceans", status: "locked", icon: "🌊", level: 2 },
    { id: 146, name: "Office", status: "locked", icon: "🏢", level: 1 },
    { id: 147, name: "Oil", status: "locked", icon: "⛽", level: 3 },
    { id: 148, name: "Online learning", status: "locked", icon: "💻", level: 2 },
    { id: 149, name: "Opinion", status: "locked", icon: "🗣️", level: 2 },
    { id: 150, name: "Optimism", status: "locked", icon: "☀️", level: 2 },
    { id: 151, name: "Parties", status: "locked", icon: "🥳", level: 1 },
    { id: 152, name: "Peace", status: "locked", icon: "🕊️", level: 2 },
    { id: 153, name: "People", status: "locked", icon: "👤", level: 1 },
    { id: 154, name: "Pets", status: "locked", icon: "🐾", level: 1 },
    { id: 155, name: "Philosophy", status: "locked", icon: "🧠", level: 3 },
    { id: 156, name: "Photography", status: "locked", icon: "📸", level: 2 },
    { id: 157, name: "Physical activity", status: "locked", icon: "🏃", level: 1 },
    { id: 158, name: "Plants", status: "locked", icon: "🌱", level: 1 },
    { id: 159, name: "Plastic", status: "locked", icon: "♻️", level: 2 },
    { id: 160, name: "Police", status: "locked", icon: "👮", level: 2 },
    { id: 161, name: "Politics", status: "locked", icon: "🗳️", level: 3 },
    { id: 162, name: "Pollution", status: "locked", icon: "🏭", level: 2 },
    { id: 163, name: "Poverty", status: "locked", icon: "🏚️", level: 3 },
    { id: 164, name: "Power", status: "locked", icon: "💪", level: 3 },
    { id: 165, name: "Pride", status: "locked", icon: "🦁", level: 2 },
    { id: 166, name: "Prison", status: "locked", icon: "⛓️", level: 3 },
    { id: 167, name: "Problems", status: "locked", icon: "⁉️", level: 1 },
    { id: 168, name: "Professions", status: "locked", icon: "🧑‍💻", level: 2 },
    { id: 169, name: "Progress", status: "locked", icon: "📈", level: 2 },
    { id: 170, name: "Psychology", status: "locked", icon: "🧠", level: 3 },
    { id: 171, name: "Public transport", status: "locked", icon: "🚇", level: 2 },
    { id: 172, name: "Reading", status: "locked", icon: "📖", level: 1 },
    { id: 173, name: "Relationships", status: "locked", icon: "🤝", level: 1 },
    { id: 174, name: "Religion", status: "locked", icon: "🛐", level: 3 },
    { id: 175, name: "Reputation", status: "locked", icon: "🌟", level: 2 },
    { id: 176, name: "Research", status: "locked", icon: "🔬", level: 3 },
    { id: 177, name: "Restaurants", status: "locked", icon: "🍽️", level: 1 },
    { id: 178, name: "Retirement", status: "locked", icon: "👴", level: 2 },
    { id: 179, name: "Risk", status: "locked", icon: "🎲", level: 2 },
    { id: 180, name: "Rivers", status: "locked", icon: "🏞️", level: 1 },
    { id: 181, name: "Robots", status: "locked", icon: "🤖", level: 2 },
    { id: 182, name: "Rural areas", status: "locked", icon: "🚜", level: 2 },
    { id: 183, name: "Safety", status: "locked", icon: "🔒", level: 1 },
    { id: 184, name: "Salaries", status: "locked", icon: "💵", level: 2 },
    { id: 185, name: "Science", status: "locked", icon: "🧪", level: 2 },
    { id: 186, name: "Sea", status: "locked", icon: "🌊", level: 1 },
    { id: 187, name: "Seasons", status: "locked", icon: "🌸", level: 1 },
    { id: 188, name: "Security", status: "locked", icon: "🛡️", level: 2 },
    { id: 189, name: "Self-improvement", status: "locked", icon: "📈", level: 2 },
    { id: 190, name: "Shopping", status: "locked", icon: "🛍️", level: 1 },
    { id: 191, name: "Sleep", status: "locked", icon: "😴", level: 1 },
    { id: 192, name: "Smartphones", status: "locked", icon: "📱", level: 1 },
    { id: 193, name: "Smoking", status: "locked", icon: "🚬", level: 2 },
    { id: 194, name: "Social media", status: "locked", icon: "📱", level: 2 },
    { id: 195, name: "Society", status: "locked", icon: "👥", level: 3 },
    { id: 196, name: "Soft skills", status: "locked", icon: "🤝", level: 3 },
    { id: 197, name: "Solar system", status: "locked", icon: "🪐", level: 2 },
    { id: 198, name: "South America", status: "locked", icon: "🌎", level: 3 },
    { id: 199, name: "Space", status: "locked", icon: "🚀", level: 3 },
    { id: 200, name: "Sports", status: "locked", icon: "⚽", level: 1 },
    { id: 201, name: "Stars", status: "locked", icon: "🌟", level: 2 },
    { id: 202, name: "Stress", status: "locked", icon: "😰", level: 1 },
    { id: 203, name: "Success", status: "locked", icon: "🏆", level: 2 },
    { id: 204, name: "Summer", status: "locked", icon: "☀️", level: 1 },
    { id: 205, name: "Superheroes", status: "locked", icon: "🦸", level: 2 },
    { id: 206, name: "Superstition", status: "locked", icon: "🍀", level: 2 },
    { id: 207, name: "Sweets", status: "locked", icon: "🍬", level: 1 },
    { id: 208, name: "Technology", status: "locked", icon: "💻", level: 2 },
    { id: 209, name: "Television", status: "locked", icon: "📺", level: 1 },
    { id: 210, name: "Temperature", status: "locked", icon: "🌡️", level: 1 },
    { id: 211, name: "Terrorism", status: "locked", icon: "💣", level: 3 },
    { id: 212, name: "Theater", status: "locked", icon: "🎭", level: 2 },
    { id: 213, name: "Time", status: "locked", icon: "⏰", level: 1 },
    { id: 214, name: "Time travel", status: "locked", icon: "🕰️", level: 3 },
    { id: 215, name: "Tourism", status: "locked", icon: "✈️", level: 2 },
    { id: 216, name: "Traditions", status: "locked", icon: "🎉", level: 2 },
    { id: 217, name: "Traffic", status: "locked", icon: "🚦", level: 1 },
    { id: 218, name: "Travel", status: "locked", icon: "✈️", level: 1 },
    { id: 219, name: "Trees", status: "locked", icon: "🌳", level: 1 },
    { id: 220, name: "Trust", status: "locked", icon: "🤝", level: 2 },
    { id: 221, name: "Truth", status: "locked", icon: "💡", level: 3 },
    { id: 222, name: "Underground", status: "locked", icon: "🚇", level: 2 },
    { id: 223, name: "Unemployment", status: "locked", icon: "😥", level: 3 },
    { id: 224, name: "Universe", status: "locked", icon: "🌌", level: 3 },
    { id: 225, name: "Vacations", status: "locked", icon: "🏖️", level: 1 },
    { id: 226, name: "Vegetables", status: "locked", icon: "🥦", level: 1 },
    { id: 227, name: "Vegetarianism", status: "locked", icon: "🥗", level: 2 },
    { id: 228, name: "Video games", status: "locked", icon: "🎮", level: 2 },
    { id: 229, name: "Violence", status: "locked", icon: "👊", level: 3 },
    { id: 230, name: "Virtue", status: "locked", icon: "😇", level: 3 },
    { id: 231, name: "Volcanoes", status: "locked", icon: "🌋", level: 2 },
    { id: 232, name: "Walking", status: "locked", icon: "🚶", level: 1 },
    { id: 233, name: "War", status: "locked", icon: "💣", level: 3 },
    { id: 234, name: "Water", status: "locked", icon: "💧", level: 2 },
    { id: 235, name: "Waterfalls", status: "locked", icon: "🏞️", level: 1 },
    { id: 236, name: "Weather", status: "locked", icon: "☁️", level: 1 },
    { id: 237, name: "Weddings", status: "locked", icon: "💒", level: 2 },
    { id: 238, name: "Weight", status: "locked", icon: "⚖️", level: 1 },
    { id: 239, name: "Wild animals", status: "locked", icon: "🐅", level: 2 },
    { id: 240, name: "Wind", status: "locked", icon: "🌬️", level: 1 },
    { id: 241, name: "Winter", status: "locked", icon: "❄️", level: 1 },
    { id: 242, name: "Women", status: "locked", icon: "👩", level: 1 },
    { id: 243, name: "Work", status: "locked", icon: "🏢", level: 1 },
    { id: 244, name: "World", status: "locked", icon: "🌍", level: 1 },
    { id: 245, name: "Writing", status: "locked", icon: "✍️", level: 2 },
    { id: 246, name: "Youth", status: "locked", icon: "👶", level: 1 },
    { id: 247, name: "Zoos", status: "locked", icon: "🦒", level: 1 },
    { id: 248, name: "Advertising", status: "locked", icon: "📣", level: 3 },
    { id: 249, name: "Air Pollution", status: "locked", icon: "😷", level: 2 },
    { id: 250, name: "Alzheimer's Disease", status: "locked", icon: "🧠", level: 3 },
    { id: 251, name: "Animal Rights", status: "locked", icon: "🐾", level: 3 },
    { id: 252, name: "Archaeology", status: "locked", icon: "🏺", level: 2 },
    { id: 253, name: "Architecture", status: "locked", icon: "🏗️", level: 2 },
    { id: 254, name: "Artificial Reefs", status: "locked", icon: "🐠", level: 3 },
    { id: 255, name: "Astrophysics", status: "locked", icon: "🌌", level: 3 },
    { id: 256, name: "Biofuels", status: "locked", icon: " biofuel", level: 3 },
    { id: 257, name: "Biotechnology", status: "locked", icon: "🔬", level: 3 },
    { id: 258, name: "Black Holes", status: "locked", icon: "⚫", level: 3 },
    { id: 259, name: "Brain Computer Interfaces", status: "locked", icon: "🧠", level: 3 },
    { id: 260, name: "Carbon Footprint", status: "locked", icon: "👣", level: 2 },
    { id: 261, name: "Climate Change", status: "locked", icon: "🌡️", level: 3 },
    { id: 262, name: "Cloud Computing", status: "locked", icon: "☁️", level: 2 },
    { id: 263, name: "Coastal Erosion", status: "locked", icon: "🌊", level: 3 },
    { id: 264, name: "Conservation", status: "locked", icon: "🌿", level: 2 },
    { id: 265, name: "Cryptocurrency", status: "locked", icon: "₿", level: 3 },
    { id: 266, name: "Cybersecurity", status: "locked", icon: "🔒", level: 3 },
    { id: 267, name: "Dark Matter", status: "locked", icon: "⚫", level: 3 },
    { id: 268, name: "Data Privacy", status: "locked", icon: "👁️‍🗨️", level: 3 }
  ];